
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team01-s26-10
owner: ucsb-cs156-s26
repo_name: team01-s26-10
pull_requests: [{"author":{"id":"U_kgDOCuipLw","is_bot":false,"login":"yuhangj554","name":"Yuhang Jiang"},"headRefName":"yj-33","number":63,"title":"yj - create controller and add /get all and /post","url":"https://github.com/ucsb-cs156-s26/team01-s26-10/pull/63"},{"author":{"id":"MDQ6VXNlcjcyMTcxNTQ2","is_bot":false,"login":"Kazu-Pang","name":"Kazu Pang"},"headRefName":"KP-30","number":62,"title":"Add MenuItemReview delete","url":"https://github.com/ucsb-cs156-s26/team01-s26-10/pull/62"},{"author":{"id":"MDQ6VXNlcjcyMTcxNTQ2","is_bot":false,"login":"Kazu-Pang","name":"Kazu Pang"},"headRefName":"KP-29","number":61,"title":"Add put for MenuItemReview","url":"https://github.com/ucsb-cs156-s26/team01-s26-10/pull/61"},{"author":{"id":"U_kgDOCyT_AA","is_bot":false,"login":"alyoon04","name":""},"headRefName":"alyoon04-UCSBDiningCommonsMenuItem-delete","number":58,"title":"Alyoon04 ucsb dining commons menu item delete","url":"https://github.com/ucsb-cs156-s26/team01-s26-10/pull/58"},{"author":{"id":"U_kgDOCyT_AA","is_bot":false,"login":"alyoon04","name":""},"headRefName":"alyoon04-UCSBDiningCommonsMenuItem-put","number":57,"title":"Alyoon04 ucsb dining commons menu item put","url":"https://github.com/ucsb-cs156-s26/team01-s26-10/pull/57"},{"author":{"id":"U_kgDOCyT_AA","is_bot":false,"login":"alyoon04","name":""},"headRefName":"alyoon04-UCSBDiningCommonsMenuItem-get-by-id","number":56,"title":"Alyoon04 ucsb dining commons menu item get by","url":"https://github.com/ucsb-cs156-s26/team01-s26-10/pull/56"},{"author":{"id":"U_kgDOCyT_AA","is_bot":false,"login":"alyoon04","name":""},"headRefName":"alyoon04-UCSBDiningCommonsMenuItem-post-and-get","number":55,"title":"Alyoon04 ucsb dining commons menu item post and get","url":"https://github.com/ucsb-cs156-s26/team01-s26-10/pull/55"},{"author":{"id":"U_kgDOCyT_AA","is_bot":false,"login":"alyoon04","name":""},"headRefName":"alyoon04-UCSBDiningCommonsMenuItem-create-db","number":54,"title":"Add UCSBDiningCommonsMenuItem entity, repository, and migration","url":"https://github.com/ucsb-cs156-s26/team01-s26-10/pull/54"},{"author":{"id":"MDQ6VXNlcjc5ODcxOTQ2","is_bot":false,"login":"EpicSRN021","name":""},"headRefName":"sn-20","number":47,"title":"Add RecommendationRequest table entity and migration","url":"https://github.com/ucsb-cs156-s26/team01-s26-10/pull/47"}]
